variable "aws_region" {}
variable "cidr_vpc" {}
variable "cidr_subnet1" {}
variable "cidr_subnet2" {}
variable "authorized_ips" {}
variable "public_sshkey_path" {}
variable "private_sshkey_path" {}
variable "az" {}
variable "az2" {}
variable "al2_private_ip" {}
variable "al2_inst_type" {}
variable "al2_cloud_init_script" {}
variable "postgresql_identifier" {}
variable "postgresql_instance_class" {}
variable "postgresql_size_in_gbs" {}
variable "postgresql_max_size_in_gbs" {}
variable "postgresql_db_name" {}
variable "postgresql_version" {}
variable "postgresql_storage_type" {}