variable "aws_region" {}
variable "pvd_cidr_vpc" {}
variable "pvd_cidr_subnet_public" {}
variable "pvd_cidr_subnet_private" {}
variable "csm_cidr_vpc" {}
variable "csm_cidr_subnet_public" {}
variable "authorized_ips" {}
variable "az" {}
variable "pvd_websrv_inst_type" {}
variable "pvd_websrv_public_sshkey_path" {}
variable "pvd_websrv_private_sshkey_path" {}
variable "pvd_websrv_cloud_init_script" {}
variable "pvd_bastion_inst_type" {}
variable "pvd_bastion_public_sshkey_path" {}
variable "pvd_bastion_private_sshkey_path" {}
variable "pvd_bastion_cloud_init_script" {}
variable "csm_bastion_inst_type" {}
variable "csm_bastion_public_sshkey_path" {}
variable "csm_bastion_private_sshkey_path" {}
variable "csm_bastion_cloud_init_script" {}
