variable "acct1_region" {}
variable "acct2_region" {}
variable "acct1_azs" {}
variable "acct2_az" {}
variable "acct1_profile" {}
variable "acct2_profile" {}
variable "acct1_pvd_cidr_vpc" {}
variable "acct1_pvd_cidr_subnets_public" {}
variable "acct1_pvd_cidr_subnets_private" {}
variable "acct2_csm_cidr_vpc" {}
variable "acct2_csm_cidr_subnet_public" {}
variable "authorized_ips" {}
variable "acct1_pvd_websrv_inst_type" {}
variable "acct1_pvd_websrv_public_sshkey_path" {}
variable "acct1_pvd_websrv_private_sshkey_path" {}
variable "acct1_pvd_websrv_cloud_init_script" {}
variable "acct1_pvd_bastion_inst_type" {}
variable "acct1_pvd_bastion_public_sshkey_path" {}
variable "acct1_pvd_bastion_private_sshkey_path" {}
variable "acct1_pvd_bastion_cloud_init_script" {}
variable "acct2_csm_bastion_inst_type" {}
variable "acct2_csm_bastion_public_sshkey_path" {}
variable "acct2_csm_bastion_private_sshkey_path" {}
variable "acct2_csm_bastion_cloud_init_script" {}
