variable "aws_region" {}
variable "cidr_vpc" {}
variable "cidr_client_subnet" {}
variable "cidr_rds_subnets" {}
variable "authorized_ips" {}
variable "public_sshkey_path" {}
variable "private_sshkey_path" {}
variable "db_client_az" {}
variable "db_client_private_ip" {}
variable "db_client_inst_type" {}
variable "db_client_cloud_init_script" {}
variable "aurora_subnets_azs" {}
variable "aurora_postgresql_db_identifier" {}
variable "aurora_postgresql_cluster_identifier" {}
variable "aurora_postgresql_engine_version" {}
variable "aurora_postgresql_username" {}
variable "aurora_postgresql_db_name" {}
variable "aurora_postgresql_size_in_gbs" {}
variable "aurora_postgresql_serverless_v2_min_acu" {}
variable "aurora_postgresql_serverless_v2_max_acu" {}
