variable "aws_region" {}
variable "cidr_vpc" {}
variable "cidr_subnet_public" {}
variable "az_subnet" {}
variable "authorized_ips" {}
variable "cpt_nodes_count" {}
variable "cpt_nodes_inst_type" {}
variable "cpt_nodes_public_sshkey_path" {}
variable "cpt_nodes_private_sshkey_path" {}
variable "cpt_nodes_cloud_init_template" {}
variable "pcs_slurm_version" {}
variable "efs_mountpoint" {}
variable "fsx_lustre_mountpoint" {}
variable "fsx_lustre_size_gb" {}
variable "fsx_lustre_version" {}
variable "scripts_dir" {}
variable "slurm_queue" {}
