variable "aws_region" {}
variable "cidr_vpc" {}
variable "cidr_subnet1" {}
variable "cidr_subnet2" {}
variable "authorized_ips" {}
variable "public_sshkey_path" {}
variable "private_sshkey_path" {}
variable "az1" {}
variable "az2" {}
variable "al2_private_ip" {}
variable "al2_inst_type" {}
variable "al2_cloud_init_script" {}
variable "docdb_identifier" {}
variable "docdb_user" {}
variable "docdb_backup_retention" {}
variable "docdb_backup_window" {}
variable "docdb_maintenance_window" {}
variable "docdb_port" {}
variable "docdb_instance_type" {}
variable "docdb_nb_of_instances" {}
variable "docdb_apply_immediately" {}
