variable "aws_region" {}
variable "cidr_vpc" {}
variable "cidr_subnet1" {}
variable "authorized_ips" {}
variable "public_sshkey_path" {}
variable "private_sshkey_path" {}
variable "az" {}
variable "al2_private_ip" {}
variable "al2_inst_type" {}
variable "al2_cloud_init_script" {}
variable "efs_mount_point" {}
