variable "aws_region" {}
variable "cidr_vpc" {}
variable "cidr_subnet1" {}
variable "cidr_subnet2" {}
variable "authorized_ips" {}
variable "public_sshkey_path" {}
variable "private_sshkey_path" {}
variable "az" {}
variable "az2" {}
variable "al2023_private_ip" {}
variable "al2023_inst_type" {}
variable "al2023_cloud_init_script" {}
variable "mysql_identifier" {}
variable "mysql_instance_class" {}
variable "mysql_size_in_gbs" {}
variable "mysql_max_size_in_gbs" {}
variable "mysql_db_name" {}
variable "mysql_version" {}
variable "mysql_storage_type" {}
variable "mysql_multi_az" {}
variable "mysql_backups_retention_days" {}
