variable "aws_region1" {}
variable "aws_region2" {}
variable "cidr_vpc_r1" {}
variable "cidr_public_r1" {}
variable "cidr_vpc_r2" {}
variable "cidr_public_r2" {}
variable "authorized_ips" {}
variable "az" {}
variable "inst_type" {}
variable "public_sshkey_path" {}
variable "private_sshkey_path" {}
variable "cloud_init_script" {}
