variable "aws_region" {}
variable "cidr_vpc1" {}
variable "cidr_public1" {}
variable "cidr_vpc2" {}
variable "cidr_public2" {}
variable "authorized_ips" {}
variable "az" {}
variable "inst_type" {}
variable "public_sshkey_path" {}
variable "private_sshkey_path" {}
variable "cloud_init_script" {}
