variable "aws_region" {}
variable "cidr_vpc" {}
variable "cidr_subnet1" {}
variable "cidr_subnet2_efa" {}
variable "authorized_ips" {}
variable "nb_instances" {}
variable "inst_private_ip" {}
variable "inst_private_ip_efa" {}
variable "inst_type" {}
variable "arch" {}
variable "linux" {}
variable "az" {}
variable "public_sshkey_path" {}
variable "private_sshkey_path" {}
variable "cloud_init_script_al" {}
variable "cloud_init_script_ubuntu" {}
