variable "aws_region" {}
variable "cidr_vpc" {}
variable "cidr_subnet1" {}
variable "cidr_subnet2" {}
variable "authorized_ips" {}
variable "public_sshkey_path" {}
variable "private_sshkey_path" {}
variable "az" {}
variable "az2" {}
variable "al2_private_ip" {}
variable "al2_inst_type" {}
variable "al2_cloud_init_script" {}
variable "oracle_identifier" {}
variable "oracle_instance_class" {}
variable "oracle_edition" {}
variable "oracle_charset" {}
variable "oracle_size_in_gbs" {}
variable "oracle_max_size_in_gbs" {}
variable "oracle_sid" {}
variable "oracle_version" {}
variable "oracle_license_model" {}
