variable "aws_region" {}
variable "account0_profile" {}
variable "account1_profile" {}
variable "account2_profile" {}
variable "acct0_cidr_vpc" {}
variable "acct0_cidr_subnet1" {}
variable "acct1_cidr_vpc" {}
variable "acct1_cidr_subnet1" {}
variable "acct2_cidr_vpc" {}
variable "acct2_cidr_subnet1" {}
variable "authorized_ips" {}
variable "az" {}
variable "inst_type" {}
variable "acct0_inst_private_ip" {}
variable "acct1_inst_private_ip" {}
variable "acct2_inst_private_ip" {}
variable "public_sshkey_path" {}
variable "private_sshkey_path" {}
variable "cloud_init_script" {}
variable "r53_domain" {}
variable "r53_sub_domain1" {}
variable "r53_sub_domain2" {}
variable "r53_host1_in_acct1" {}
variable "r53_host2_in_acct2" {}
variable "r53_endp_inb_ip1" {}
variable "r53_endp_inb_ip2" {}
variable "r53_endp_outb_ip1" {}
variable "r53_endp_outb_ip2" {}
